---
- hosts: pvenodes
  become: true
  gather_facts: false
  vars_files:
    - ../vars/main.yml
  tasks:

    - name: Create servers using loop
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ node }}"
        vmid: 103
        clone: template
        storage: local-lvm
        full: true
        tags: 'demo,dsc'
        timeout: 3000
        newid: "{{ item.newid }}"
        name: "{{ item.name }}"
      register: vm_cloned
      loop:
        - name: srvdc1
          newid: 9001
          ip: 192.168.1.241
          gw: 192.168.1.254
        - name: srvdsc1
          newid: 9002
          ip: 192.168.1.242
          gw: 192.168.1.254
        - name: srvclient1
          newid: 9003
          ip: 192.168.1.243
          gw: 192.168.1.254
        - name: srvclient2
          newid: 9004
          ip: 192.168.1.244
          gw: 192.168.1.254

    - name : Set networking info
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ node }}"
        vmid: "{{ item.newid }}"
        name: "{{ item.name }}"
        ipconfig:
          ipconfig0: 'gw={{ item.gw }},ip={{ item.ip }}/24'
        update: true
      when:
        - vm_cloned.changed == true
      loop:
        - name: srvdc1
          newid: 9001
          ip: 192.168.1.241
          gw: 192.168.1.254
        - name: srvdsc1
          newid: 9002
          ip: 192.168.1.242
          gw: 192.168.1.254
        - name: srvclient1
          newid: 9003
          ip: 192.168.1.243
          gw: 192.168.1.254
        - name: srvclient2
          newid: 9004
          ip: 192.168.1.244
          gw: 192.168.1.254

    - name : Start VM 
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ node }}"
        name: "{{ item }}"
        state: started
      loop:
        - srvdc1
        - srvdsc1
        - srvclient1
        - srvclient2
