---
# Description
- name: pve auto configuration
  hosts: pve
  gather_facts: true
  vars_files: 
    - ./vars/pve.yml  
  tasks:
    - name: Delete enterprise repository
      ansible.builtin.file:
        state: absent
        path: /etc/apt/sources.list.d/pve-enterprise.list

    - name: Disable enterprise repository in ceph
      lineinfile:
        path: /etc/apt/sources.list.d/ceph.list
        # The String to Search
        regexp: "^deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise" 
        # The String to Replace
        line: "# deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise"
        state: present

    - name: Enable no-subscription repository
      lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        state: present

    - name: Update and upgrade apt packages
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install the latest version of wireless-tools
      ansible.builtin.package:
        name:
          - wireless-tools
        state: latest

    - name: Install the latest version of python3-proxmoxer
      ansible.builtin.package:
        name:
          - python3-proxmoxer
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Copy interface file
      ansible.builtin.copy:
        src: ./files/interfaces
        dest: /etc/network/interfaces

    - name: restart network service
      shell: systemctl restart networking
      
    - name: map nas storage
      blockinfile:
        dest: /etc/pve/storage.cfg
        block: |

          nfs: nas-iso
            export {{ nas_path }}
            path /mnt/pve/nas-iso
            server {{ nas_ip }}
            content iso
            prune-backups keep-all=1

          nfs: nas-backup
            export {{ nas_path }}
            path /mnt/pve/nas-backup
            server {{ nas_ip }}
            content backup
            prune-backups keep-all=1
