---
# Description
- name: pve auto configuration
  hosts: pve
  gather_facts: true
  vars_files: 
    - ./vars/pve.yml  
  tasks:
    - name: Install the latest version of wireless-tools
      ansible.builtin.package:
        name:
          - wireless-tools
        state: latest
    - name: Install the latest version of python3-proxmoxer
      ansible.builtin.package:
        name:
          - python3-proxmoxer
        state: latest
    - name: Copy interface file
      ansible.builtin.copy:
        src: ./files/interfaces
        dest: /etc/network/interfaces
    - name : restart network service
      shell: systemctl restart networking